baseurl = "https://heck1.github.io/blog/"
publishDir = "docs"
languageCode = "en-us"
title = "Lukas Heck"

theme = "Hugo-lithium"


googleAnalytics = "UA-121885797-1"
disqusShortname = "Lukas Heck"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Lukas Heck"
    url = "/about/"
    weight = 1
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"


[[menu.main]]
    name = "GitHub"
    url = "https://github.com/heck1/"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"

[[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/lukasheck/"

[[menu.main]]
    name = "StackOverflow"
    url = "https://stackoverflow.com/users/9294787/heck1"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-stack-overflow\"></i>"


[params]
    description = "Lukas Heck - Data Analyst and Political Scientist"
  url = "/about/"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
  url = "lh.png"
  img = "/about/"
  width = 50
    height = 50
    alt = "Lukas Heck"
